### ISSUE TITLE
error with using fluent-plugin-snmptrap, with the latest version of fluentd (fluentd 0.14.8)

### ISSUE THREAD

**Issue by psarupria** [Bigel0w/fluent-plugin-snmptrap#8]
I get the following error message while using snmptrap input plugin (fluent-plugin-snmptrap) with the latest version of fluentd (fluentd 0.14.8), the fix for this adding _require 'fluent/input_' in the "in_snmptrap.rb", but Its better if we get a update with the gem !!!

2016-11-04 12:09:34 +0530 [info]: adding source type="snmptrap"
**2016-11-04 12:09:34 +0530 [error]: unexpected error error="uninitialized constant Fluent::Input"**
  2016-11-04 12:09:34 +0530 [error]: /var/lib/gems/2.2.0/gems/fluent-plugin-snmptrap-0.0.1/lib/fluent/plugin/in_snmptrap.rb:2:in `<module:Fluent>'
  2016-11-04 12:09:34 +0530 [error]: /var/lib/gems/2.2.0/gems/fluent-plugin-snmptrap-0.0.1/lib/fluent/plugin/in_snmptrap.rb:1:in `<top (required)>'
  2016-11-04 12:09:34 +0530 [error]: /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2016-11-04 12:09:34 +0530 [error]: /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'

**Comment by psarupria** [comment]
Any fast update on this issue will be appreciated !!
